/*
 * File: app/view/Index.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Index', {
	extend: 'Ext.Container',
	alias: 'widget.index',

	requires: [
		'MyApp.view.IndexViewModel',
		'MyApp.view.IndexViewController',
		'Ext.field.TextArea',
		'Ext.grid.Grid',
		'Ext.grid.column.RowNumberer',
		'Ext.grid.cell.Text',
		'Ext.XTemplate'
	],

	controller: 'index',
	viewModel: {
		type: 'index'
	},
	padding: 3,
	scrollable: true,

	items: [
		{
			xtype: 'container',
			defaults: {
				margin: '0 5'
			},
			items: [
				{
					xtype: 'container',
					bind: {
						html: '{step1Text}'
					}
				},
				{
					xtype: 'textareafield',
					reference: 'keywordsEditor',
					border: false,
					height: 343,
					itemId: 'keywordsEditor',
					shadow: true,
					margin: '5 7 7 5',
					label: 'Put keywords one by line',
					bind: {
						hidden: '{!editMode}'
					}
				},
				{
					xtype: 'grid',
					headerContainer: {
						xtype: 'headercontainer',
						style: 'opacity: 0;'
					},
					reference: 'keywordsGrid',
					height: 343,
					itemId: '',
					shadow: true,
					margin: '5 7 7 5',
					store: 'keywords',
					hideHeaders: true,
					bind: {
						hidden: '{editMode}'
					},
					columns: [
						{
							xtype: 'rownumberer',
							width: 50
						},
						{
							xtype: 'gridcolumn',
							flex: 1,
							dataIndex: 'keyword',
							cell: {
								xtype: 'textcell',
								bodyStyle: 'font-weight: bold;'
							}
						},
						{
							xtype: 'gridcolumn',
							renderer: function(value, record, dataIndex, cell, column) {
								return MyApp.view.IndexViewController.freqFormatter(value);
							},
							width: 85,
							align: 'right',
							cell: {
								xtype: 'gridcell',
								encodeHtml: false,
								bodyStyle: 'font-size: small;'
							},
							dataIndex: 'frequency'
						},
						{
							xtype: 'gridcolumn',
							width: 40,
							cell: {
								tools: [
									{
										iconCls: 'fa fa-trash',
										handler: 'onKeywordsDelete'
									}
								]
							},
							dataIndex: 'controls'
						}
					]
				},
				{
					xtype: 'container',
					items: [
						{
							text: 'Import from file',
							iconCls: 'fa fa-upload',
							handler: 'onKeywordsImportFromFile',
							plugins: {
								responsive: true
							},
							responsiveConfig: {
								wide: {
									hidden: false
								},
								tall: {
									hidden: true
								}
							}
						},
						{
							text: 'Analyze competitors',
							iconCls: 'fa fa-pie-chart',
							handler: 'onKeywordsAnalyzeCompetitors',
							bind: {
								hidden: '{editMode}'
							}
						},
						{
							xtype: 'container',
							flex: 1
						},
						{
							text: 'Edit',
							iconCls: 'fa fa-pencil-square-o',
							handler: 'onKeywordsEdit',
							bind: {
								hidden: '{editMode}'
							}
						},
						{
							text: 'Cancel',
							handler: 'onKeywordsCancel',
							hidden: true,
							bind: {
								hidden: '{!editMode}'
							}
						},
						{
							text: 'Save',
							iconCls: 'fa fa-floppy-o',
							handler: 'onKeywordsSave',
							bind: {
								hidden: '{!editMode}'
							}
						}
					],
					margin: '20 5 0',
					padding: '0 5 0 0',
					defaults: {
						xtype: 'button'
					},
					layout: 'hbox'
				}
			]
		},
		{
			xtype: 'container',
			margin: '20 0 0 0',
			defaults: {
				margin: '0 5'
			},
			items: [
				{
					xtype: 'container',
					bind: {
						html: '{step2Text}'
					}
				},
				{
					xtype: 'grid',
					headerContainer: {
						xtype: 'headercontainer',
						style: 'opacity: 0;'
					},
					reference: 'searchEnginesGrid',
					shadow: true,
					margin: '5 7 7 5',
					store: 'searchEngines',
					infinite: false,
					hideHeaders: true,
					columns: [
						{
							xtype: 'gridcolumn',
							flex: 1,
							tpl: Ext.create('Ext.XTemplate', 
								'<div class="se-block">',
								'	<div class="se-pic">{[this.img(values.seId)]}</div>',
								'	<div class="se-text">',
								'		<div class="se-name">{name}</div>',
								'		<div class="se-info">{info}</div>',
								'	</div>',
								'</div>',
								{
									img: function(seId) {
										return MyApp.shared.seImgTagBuilder(seId);
									}
								}
							),
							cell: {
								xtype: 'gridcell',
								encodeHtml: false
							},
							dataIndex: 'name'
						},
						{
							xtype: 'gridcolumn',
							width: 80,
							cell: {
								xtype: 'gridcell',
								encodeHtml: false,
								tools: [
									{
										zone: 'end',
										iconCls: 'fa fa-cog',
										handler: 'onSearchEngineEdit'
									},
									{
										zone: 'end',
										iconCls: 'fa fa-trash',
										handler: 'onSearchEngineRemove'
									}
								]
							},
							text: 'MyColumn'
						}
					]
				},
				{
					xtype: 'container',
					items: [
						{
							text: 'add',
							iconCls: 'fa fa-plus',
							handler: 'onSearchEngineAdd'
						}
					],
					margin: '20 5 0',
					padding: '0 5',
					defaults: {
						xtype: 'button'
					},
					layout: {
						type: 'hbox',
						pack: 'end'
					}
				}
			]
		},
		{
			xtype: 'container',
			height: 100
		}
	],

	initialize: function() {
		this.callParent();
		this.getController().initialize();
	}

});