/*
 * File: app/view/keywordsDialog.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.keywordsDialog', {
	extend: 'Ext.Dialog',
	alias: 'widget.keywordsdialog',

	requires: [
		'MyApp.view.keywordsDialogViewModel',
		'MyApp.view.keywordsDialogViewController',
		'Ext.field.Panel',
		'Ext.field.Text',
		'Ext.Toolbar',
		'Ext.grid.Grid',
		'Ext.grid.column.Check'
	],

	controller: 'keywordsdialog',
	viewModel: {
		type: 'keywordsdialog'
	},
	height: '90%',
	width: '90%',
	maxWidth: 700,
	layout: 'fit',
	bodyStyle: 'padding: 0;',
	closable: true,

	bind: {
		title: '{dialogTitle}'
	},
	items: [
		{
			xtype: 'container',
			publishes: 'activeItemIndex',
			reference: 'cards',
			layout: {
				type: 'card',
				animation: 'slide'
			},
			items: [
				{
					xtype: 'fieldpanel',
					reference: 'domainsForm',
					defaults: {
						cls: 'myapp-textfield-label-active'
					},
					bodyPadding: 15,
					items: [
						{
							xtype: 'textfield',
							name: 'competitor1',
							label: 'Competitor #1',
							value: 'google.com'
						},
						{
							xtype: 'textfield',
							name: 'competitor2',
							label: 'Competitor #2'
						},
						{
							xtype: 'textfield',
							name: 'competitor3',
							label: 'Competitor #3'
						},
						{
							xtype: 'textfield',
							name: 'competitor4',
							label: 'Competitor #4'
						},
						{
							xtype: 'textfield',
							name: 'competitor5',
							label: 'Competitor #5'
						},
						{
							xtype: 'toolbar',
							items: [
								'->',
								{
									text: 'next',
									handler: 'onNext'
								}
							],
							cls: 'myapp-no-padding-toolbar',
							docked: 'bottom'
						}
					]
				},
				{
					xtype: 'container',
					layout: 'vbox',
					items: [
						{
							xtype: 'container',
							items: [
								{
									xtype: 'button',
									text: 'Select All',
									handler: 'onSelectAll'
								}
							]
						},
						{
							xtype: 'grid',
							headerContainer: {
								xtype: 'headercontainer',
								style: 'opacity: 0;'
							},
							flex: 1,
							reference: 'keywordsGrid',
							store: 'keywordsAdditional',
							hideHeaders: true,
							columns: [
								{
									xtype: 'checkcolumn',
									width: 30,
									dataIndex: 'checked'
								},
								{
									xtype: 'gridcolumn',
									flex: 1,
									dataIndex: 'keyword'
								},
								{
									xtype: 'gridcolumn',
									width: 85,
									align: 'right',
									cell: {
										xtype: 'gridcell',
										encodeHtml: false,
										bodyStyle: 'font-size: small;'
									},
									dataIndex: 'frequency',
									formatter: 'myFreq'
								}
							]
						},
						{
							xtype: 'toolbar',
							items: [
								{
									text: 'back',
									handler: 'onPrev'
								},
								'->',
								{
									text: 'add keywords',
									handler: 'onAddKeywords'
								}
							],
							cls: 'myapp-no-padding-toolbar',
							docked: 'bottom'
						}
					]
				}
			]
		}
	],
	listeners: {
		destroy: 'onDialogDestroy'
	}

});