/*
 * File: app/view/keywordsDialogViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.keywordsDialogViewController', {
	extend: 'Ext.app.ViewController',
	alias: 'controller.keywordsdialog',

	onNext: function(button, e) {
		let view = this.view;

		let domains = Ext.Array.clean(Ext.Object.getValues(view.lookup('domainsForm').getValues()));

		let keywordsStore = Ext.data.StoreManager.lookup('keywords');
		let keywords = keywordsStore.getData().getValues('keyword', 'data');

		view.setMasked({xtype: 'loadmask'});

		Ext.Ajax.request({

			method: 'post',
			url: 'https://cors-anywhere.herokuapp.com/https://spyserp.com/panel/apiclient',

			jsonData: {method:"projectCustom",	domain: domains, keywords:keywords, multi:1}

		}).then((response) => {

			let data = Ext.decode(response.responseText);
			console.dir(data);

			if (data.success !== false)
			{
				this.lookup('cards').setActiveItem(1);

				let additionalKeywordsStore = Ext.data.StoreManager.lookup('keywordsAdditional');
				additionalKeywordsStore.loadRawData(data);
			}
			else
			{
				Ext.Msg.alert('Error', data.msg || 'Unknown error');
			}

		}).always(() => {

			view.unmask();

		}).otherwise((response) => {

			Ext.Msg.alert('error', response.status + ' ' + response.statusText + '<br>' + response.responseText);

		});
	},

	onPrev: function(button, e) {
		this.lookup('cards').setActiveItem(0);
	},

	onSelectAll: function(button, e) {
		this._selected = !this._selected;

		let additionalKeywordsStore = Ext.data.StoreManager.lookup('keywordsAdditional');
		additionalKeywordsStore.each((rec) => {
			rec.set('checked', this._selected);
		});
	},

	onAddKeywords: function(button, e) {
		let keywordsStore = Ext.data.StoreManager.lookup('keywords');
		let additionalKeywordsStore = Ext.data.StoreManager.lookup('keywordsAdditional');

		keywordsStore.beginUpdate();
		additionalKeywordsStore.each((rec) => {
			if (rec.get('checked'))
				keywordsStore.add(rec.copy());
		});
		keywordsStore.endUpdate();

		this.view.close();
	},

	onDialogDestroy: function(eOpts) {
		Ext.data.StoreManager.lookup('keywordsAdditional').removeAll();
	}

});