/*
 * File: app/view/searchEngineDialog.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.searchEngineDialog', {
	extend: 'Ext.Dialog',
	alias: 'widget.searchenginedialog',

	requires: [
		'MyApp.view.searchEngineDialogViewModel',
		'MyApp.view.searchEngineDialogViewController',
		'Ext.field.Panel',
		'Ext.Toolbar'
	],

	controller: 'searchenginedialog',
	viewModel: {
		type: 'searchenginedialog'
	},
	height: '90%',
	width: '90%',
	maxHeight: 750,
	maxWidth: 700,
	layout: 'fit',
	bodyStyle: 'padding: 0;',
	closable: true,

	items: [
		{
			xtype: 'fieldpanel',
			reference: 'searchEngineForm',
			defaults: {
				cls: 'myapp-textfield-label-active'
			},
			bodyPadding: 15
		},
		{
			xtype: 'toolbar',
			items: [
				'->',
				{
					text: 'Cancel',
					handler: 'onCancel'
				},
				{
					text: 'Add',
					ui: 'action',
					handler: 'onSave',
					reference: 'saveButton'
				}
			],
			docked: 'bottom'
		}
	],

	initialize: function() {
		this.callParent();
		this.getController().initialize();
	}

});