/*
 * File: app/model/Keyword.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Keyword', {
	extend: 'Ext.data.Model',
	alias: 'model.keyword',

	requires: [
		'Ext.data.field.String',
		'Ext.data.field.Number',
		'Ext.data.field.Boolean'
	],


	fields: [
		{
			type: 'int',
			mapping: 'key_id',
			name: 'id'
		},
		{
			type: 'string',
			mapping: 'key_title',
			name: 'keyword'
		},
		{
			type: 'float',
			name: 'frequency'
		},
		{
			type: 'boolean',
			name: 'checked'
		}
	]

});